node:
	parity --config config/node.toml

dev:
	parity --config config/dev.toml

api:
	parity --config config/api.toml

authority:
	parity --config config/authority.toml

explorer:
	parity --config config/explorer.toml
