node:
	parity --config config/node.toml

dev:
	parity --config config/dev.toml

api:
	parity --config config/api.toml

explorer:
	parity --config config/explorer.toml

light:
	parity --config config/light.toml
