[parity]
base_path = "./chain-data"
no_persistent_txqueue = true

[rpc]
disable = false
apis = ["web3", "eth", "net", "traces", "rpc", "pubsub"]
interface = "127.0.0.1"
hosts = ["all"]
cors=["all"]
port = 8545
processing_threads = 4

[websockets]
disable = false
apis = ["web3", "eth", "net", "traces", "rpc", "pubsub"]
origins = ["all"]
hosts = ["all"]
port = 8546
interface = "127.0.0.1"

[ipc]
disable = true

[ui]
disable = true

[network]
discovery = true
warp = false
# When warp enabled never attempt regular sync before warping to block NUM.
warp_barrier = 9000000
# Parity will try to maintain connection to at least 50 peers.
min_peers = 200
# Parity will maintain at most 100 peers.
max_peers = 400

[mining]
force_sealing = true
reseal_on_txs = "none"
min_gas_price = 1000000000
gas_floor_target = "10000000"

[footprint]
fat_db = "off"
num_verifiers = 8
# Number of threads will vary depending on the workload. Not guaranteed to be faster.
scale_verifiers = true
# Prune old state data. Maintains journal overlay - fast but extra 50MB of memory used.
pruning = "fast"
# Will keep up to 4096MB data in Database cache.
cache_size_db = 4096
# Will keep up to 1024MB data in Blockchain cache.
cache_size_blocks = 1024
# Will keep up to 1024MB of blocks in block import queue.
cache_size_queue = 1024
# Will keep up to 1024MB data in State cache.
cache_size_state = 1024

[misc]
log_file = "./parity.log"
# Logging pattern (`<module>=<level>`, e.g. `own_tx=trace`).
logging = "own_tx,tx_queue=trace"
color = true
