[parity]
base_path = "./chain-data"
no_persistent_txqueue = true
keys_path = "./keys"

[rpc]
disable = false
apis = ["all"]
interface = "127.0.0.1"
hosts = ["all"]
cors=["all"]

[websockets]
disable = false
apis = ["all"]
origins = ["none"]
hosts = ["all"]
interface = "127.0.0.1"

[ipc]
disable = true

[account]
unlock = ["0x1824ffbe5da19fa1d4b9b77a18f355393c67034d"]
password = ["./keys/all.pwd"]

[ui]
disable = true

[network]
discovery = true
warp = true

[misc]
log_file = "./parity.log"
# Logging pattern (`<module>=<level>`, e.g. `own_tx=trace`).
logging = "own_tx,tx_queue,rpc=trace"
