[parity]
base_path = "./chain-data"
chain = "./spec.json"
no_persistent_txqueue = true
keys_path = "./keys"

[rpc]
disable = false
apis = ["web3", "eth", "net", "traces", "rpc", "pubsub"]
interface = "127.0.0.1"
hosts = ["all"]
cors=["all"]
port = 8545
server_threads = 2

[websockets]
disable = false
apis = ["web3", "eth", "net", "traces", "rpc", "pubsub"]
origins = ["all"]
hosts = ["all"]
port = 8546
interface = "127.0.0.1"

[ipc]
disable = true

[ui]
disable = true

[network]
discovery = true
warp = true

[mining]
force_sealing = true
reseal_on_txs = "none"
min_gas_price = 1000000000
gas_floor_target = "8700000"

[footprint]
fat_db = "off"

[misc]
log_file = "./parity.log"
# Logging pattern (`<module>=<level>`, e.g. `own_tx=trace`).
logging = "own_tx,tx_queue=trace"
